config/routes.rb
Rails.application.routes.draw do
  resources :trabajos
  resources :usuarios
  resources :diccionarios
  resources :articulos
  
  root :to => redirect('/es/inicio')
  get 'es/inicio' => 'es#home'
  get 'es/colores-y-foliados'=> 'es#coloresFoliados'
  get 'es/nuestraEmpresa'=> 'es#nuestraEmpresa'
  get 'es/nuestrosProductos'=> 'es#nuestrosProductos'
  get 'es/garantia'=> 'es#garantia'
  get 'es/materialesCalidad'=> 'es#materialesCalidad'
  get 'es/productos'=> 'es#productos'
  get 'es/ventanas'=> 'es#ventanas'
  get 'es/puertas'=> 'es#puertas'
  get 'es/cerramientos'=> 'es#cerramientos'
  get 'es/cristalInteligente'=> 'es#cristalInteligente'
  get 'es/trabajos'=> 'es#trabajos'
  get 'es/blog'=> 'es#blog'
  get 'es/articuloBlog/:id'=> 'es#articuloBlog', as: :articuloBlogEs
  get 'es/avisoLegal' => 'es#avisoLegal'
    get 'en/home' => 'en#home'
  get 'en/colors-and-foliated'=> 'en#coloresFoliados'
  get 'en/ourCompany'=> 'en#nuestraEmpresa'
  get 'en/ourProducts'=> 'en#nuestrosProductos'
  get 'en/warranty'=> 'en#garantia'
  get 'en/qualityMaterials'=> 'en#materialesCalidad'
  get 'en/products'=> 'en#productos'
  get 'en/windows'=> 'en#ventanas'
  get 'en/doors'=> 'en#puertas'
  get 'en/enclosures'=> 'en#cerramientos'
  get 'en/intelligentGlass'=> 'en#cristalInteligente'
  get 'en/works'=> 'en#trabajos'
  get 'en/blog'=> 'en#blog'
  get 'en/articleBlog/:id'=> 'en#articuloBlog', as: :articuloBlogEn
    get 'fr/home' => 'fr#home'
  get 'fr/couleurs-et-feuillete'=> 'fr#coloresFoliados'
  get 'fr/notreSociete'=> 'fr#nuestraEmpresa'
  get 'fr/nosProduits'=> 'fr#nuestrosProductos'
  get 'fr/garantie'=> 'fr#garantia'
  get 'fr/materiauxQualite'=> 'fr#materialesCalidad'
  get 'fr/produits'=> 'fr#productos'
  get 'fr/fenetres'=> 'fr#ventanas'
  get 'fr/portes'=> 'fr#puertas'
  get 'fr/boitiers'=> 'fr#cerramientos'
  get 'fr/verreIntelligent'=> 'fr#cristalInteligente'
  get 'fr/travaux'=> 'fr#trabajos'
  get 'fr/blog'=> 'fr#blog'
  get 'fr/articleBlog/:id'=> 'fr#articuloBlog', as: :articuloBlogFr
    get 'de/home' => 'de#home'
  get 'de/farben-und-foliated'=> 'de#coloresFoliados'
  get 'de/unserUnternehmen'=> 'de#nuestraEmpresa'
  get 'de/unsereProdukte'=> 'de#nuestrosProductos'
  get 'de/garantie'=> 'de#garantia'
  get 'de/werkstoffeQualitat'=> 'de#materialesCalidad'
  get 'de/produkte'=> 'de#productos'
  get 'de/fenster'=> 'de#ventanas'
  get 'de/turen'=> 'de#puertas'
  get 'de/gehause'=> 'de#cerramientos'
  get 'de/intelligentGlas'=> 'de#cristalInteligente'
  get 'de/arbeit'=> 'de#trabajos'
  get 'de/blog'=> 'de#blog'
  get 'de/artikelBlog/:id'=> 'de#articuloBlog', as: :articuloBlogDe
  
  get 'delDiccionario/:id'=> 'diccionarios#destroy', as: :delDicionario
  get 'delUsuario/:id'=> 'usuarios#destroy', as: :delUsuario
  get 'delArticulo/:id'=> 'articulos#destroy', as: :delArticulo
  get 'delTrabajo/:id'=> 'trabajos#destroy', as: :delTrabajo
  get 'login'=>'es#login'
  post 'entrar'=>'es#entrar'
  get 'salir'=>'es#salir'
  
  get '*path' => redirect('/es/inicio')

end

app/controllers/fr_controller.rb
class FrController < ApplicationController
   def home
    current_user
    @traducciones=Diccionario.all
  end
  def nuestraEmpresa
    current_user
        @traducciones=Diccionario.all
  end
  def nuestrosProductos
    current_user
        @traducciones=Diccionario.all
  end
  def garantia
    current_user
        @traducciones=Diccionario.all
  end
  def materialesCalidad
    current_user
        @traducciones=Diccionario.all
  end
  def productos
    current_user
        @traducciones=Diccionario.all
  end
  def ventanas
    current_user
        @traducciones=Diccionario.all
  end
  def puertas
    current_user
        @traducciones=Diccionario.all
  end
  def cerramientos
    current_user
        @traducciones=Diccionario.all
  end
  def cristalInteligente
    current_user
        @traducciones=Diccionario.all
  end
  def trabajos
    current_user
        @traducciones=Diccionario.all
    @trabajos = Trabajo.all.sort_by{|e| e[:nombreTrabajo]}
  end
  def blog
    current_user
    @articulosBlog=Articulo.all.reverse
  end
  def articuloBlog
    current_user
    @articulo=Articulo.find(params[:id])
  end
  def coloresFoliados
    current_user
        @traducciones=Diccionario.all
  end
end

app/helpers/fr_helper.rb
module FrHelper
end

app/views/fr/blog.html.erb
<!DOCTYPE html>
<html lang="fr">
	<head>
		<title>Blog</title>
		<meta charset="utf-8">
		<meta name="format-detection" content="telephone=no"/>
		<% activo "","","","","","active" %>
		<% idioma "fr" %>
		<% user @current_user %>
	</head>
	<body>
		<div class="page">
			<!--========================================================
			CONTENT
			=========================================================-->
			<main>
				<section class="well well__ins2 bg-primary">
					<div class="container">
						<h3 class="primary-color">Artículos</h3>
						<% contador=0%>
						<%if @articulosBlog!=nil%>
						<% @articulosBlog.each do |articulo| %>
						<% contador=contador+1%>
						<%if contador==1%>
						<div class="row">
							<%end%>
							<div class="grid_4">
								<div class="box2">
									<%=link_to articuloBlogEs_path(articulo.id) do%>
									<img src="../uploads/<%= articulo.foto %>" alt="" style="width: 100%; height: auto;"/>
									<%end%>

									<div class="box2_cnt">
										<h5 class="strong"> <%=link_to articuloBlogEs_path(articulo.id) do%><%= articulo.tituloEs %><%end%> </h5>

										<p class="big">
											<%= articulo.subtituloEs %>
										</p>
										<p class="fa fa-calendar">
											<%= articulo.created_at.to_s[0..10].split("-").reverse.join("/") %>
										</p>
									</div>
								</div>
							</div>
							<%if contador==3 or articulo.id==Articulo.first.id%>
							<% contador=0%>
						</div>
						<%end%>
						<%end%><%end%>
					</div>

				</section>

			</main>
		</div>
	</body>
</html>

app/views/fr/cerramientos.html.erb
<!DOCTYPE html>
<html lang="fr">
	<head>
		<title><%=@traducciones.find(80).frances%></title>
		<meta charset="utf-8">
		<meta name="format-detection" content="telephone=no"/>
		<% activo "","","","active","","" %>
		<% idioma "fr" %>
		<% user @current_user %>
	</head>
	<body>
		<script>
			jssor_slider1_starter = function(containerId) {
				var _CaptionTransitions = [];
				_CaptionTransitions["L"] = {
					$Duration : 900,
					x : 0.6,
					$Easing : {
						$Left : $JssorEasing$.$EaseInOutSine
					},
					$Opacity : 2
				};
				_CaptionTransitions["R"] = {
					$Duration : 900,
					x : -0.6,
					$Easing : {
						$Left : $JssorEasing$.$EaseInOutSine
					},
					$Opacity : 2
				};
				_CaptionTransitions["T"] = {
					$Duration : 900,
					y : 0.6,
					$Easing : {
						$Top : $JssorEasing$.$EaseInOutSine
					},
					$Opacity : 2
				};
				_CaptionTransitions["B"] = {
					$Duration : 900,
					y : -0.6,
					$Easing : {
						$Top : $JssorEasing$.$EaseInOutSine
					},
					$Opacity : 2
				};
				_CaptionTransitions["ZMF|10"] = {
					$Duration : 900,
					$Zoom : 11,
					$Easing : {
						$Zoom : $JssorEasing$.$EaseOutQuad,
						$Opacity : $JssorEasing$.$EaseLinear
					},
					$Opacity : 2
				};
				_CaptionTransitions["RTT|10"] = {
					$Duration : 900,
					$Zoom : 11,
					$Rotate : 1,
					$Easing : {
						$Zoom : $JssorEasing$.$EaseOutQuad,
						$Opacity : $JssorEasing$.$EaseLinear,
						$Rotate : $JssorEasing$.$EaseInExpo
					},
					$Opacity : 2,
					$Round : {
						$Rotate : 0.8
					}
				};
				_CaptionTransitions["RTT|2"] = {
					$Duration : 900,
					$Zoom : 3,
					$Rotate : 1,
					$Easing : {
						$Zoom : $JssorEasing$.$EaseInQuad,
						$Opacity : $JssorEasing$.$EaseLinear,
						$Rotate : $JssorEasing$.$EaseInQuad
					},
					$Opacity : 2,
					$Round : {
						$Rotate : 0.5
					}
				};
				_CaptionTransitions["RTTL|BR"] = {
					$Duration : 900,
					x : -0.6,
					y : -0.6,
					$Zoom : 11,
					$Rotate : 1,
					$Easing : {
						$Left : $JssorEasing$.$EaseInCubic,
						$Top : $JssorEasing$.$EaseInCubic,
						$Zoom : $JssorEasing$.$EaseInCubic,
						$Opacity : $JssorEasing$.$EaseLinear,
						$Rotate : $JssorEasing$.$EaseInCubic
					},
					$Opacity : 2,
					$Round : {
						$Rotate : 0.8
					}
				};
				_CaptionTransitions["CLIP|LR"] = {
					$Duration : 900,
					$Clip : 15,
					$Easing : {
						$Clip : $JssorEasing$.$EaseInOutCubic
					},
					$Opacity : 2
				};
				_CaptionTransitions["MCLIP|L"] = {
					$Duration : 900,
					$Clip : 1,
					$Move : true,
					$Easing : {
						$Clip : $JssorEasing$.$EaseInOutCubic
					}
				};
				_CaptionTransitions["MCLIP|R"] = {
					$Duration : 900,
					$Clip : 2,
					$Move : true,
					$Easing : {
						$Clip : $JssorEasing$.$EaseInOutCubic
					}
				};

				var options = {
					$FillMode : 2, //[Optional] The way to fill image in slide, 0 stretch, 1 contain (keep aspect ratio and put all inside slide), 2 cover (keep aspect ratio and cover whole slide), 4 actual size, 5 contain for large image, actual size for small image, default value is 0
					$AutoPlay : true, //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
					$AutoPlayInterval : 4000, //[Optional] Interval (in milliseconds) to go for next slide since the previous stopped if the slider is auto playing, default value is 3000
					$PauseOnHover : 1, //[Optional] Whether to pause when mouse over if a slider is auto playing, 0 no pause, 1 pause for desktop, 2 pause for touch device, 3 pause for desktop and touch device, 4 freeze for desktop, 8 freeze for touch device, 12 freeze for desktop and touch device, default value is 1

					$ArrowKeyNavigation : true, //[Optional] Allows keyboard (arrow key) navigation or not, default value is false
					$SlideEasing : $JssorEasing$.$EaseOutQuint, //[Optional] Specifies easing for right to left animation, default value is $JssorEasing$.$EaseOutQuad
					$SlideDuration : 800, //[Optional] Specifies default duration (swipe) for slide in milliseconds, default value is 500
					$MinDragOffsetToSlide : 20, //[Optional] Minimum drag offset to trigger slide , default value is 20
					//$SlideWidth: 600,                                 //[Optional] Width of every slide in pixels, default value is width of 'slides' container
					//$SlideHeight: 300,                                //[Optional] Height of every slide in pixels, default value is height of 'slides' container
					$SlideSpacing : 0, //[Optional] Space between each slide in pixels, default value is 0
					$DisplayPieces : 1, //[Optional] Number of pieces to display (the slideshow would be disabled if the value is set to greater than 1), the default value is 1
					$ParkingPosition : 0, //[Optional] The offset position to park slide (this options applys only when slideshow disabled), default value is 0.
					$UISearchMode : 1, //[Optional] The way (0 parellel, 1 recursive, default value is 1) to search UI components (slides container, loading screen, navigator container, arrow navigator container, thumbnail navigator container etc).
					$PlayOrientation : 1, //[Optional] Orientation to play slide (for auto play, navigation), 1 horizental, 2 vertical, 5 horizental reverse, 6 vertical reverse, default value is 1
					$DragOrientation : 1, //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)

					$CaptionSliderOptions : {//[Optional] Options which specifies how to animate caption
						$Class : $JssorCaptionSlider$, //[Required] Class to create instance to animate caption
						$CaptionTransitions : _CaptionTransitions, //[Required] An array of caption transitions to play caption, see caption transition section at jssor slideshow transition builder
						$PlayInMode : 1, //[Optional] 0 None (no play), 1 Chain (goes after main slide), 3 Chain Flatten (goes after main slide and flatten all caption animations), default value is 1
						$PlayOutMode : 3 //[Optional] 0 None (no play), 1 Chain (goes before main slide), 3 Chain Flatten (goes before main slide and flatten all caption animations), default value is 1
					},

					$BulletNavigatorOptions : {//[Optional] Options to specify and enable navigator or not
						$Class : $JssorBulletNavigator$, //[Required] Class to create navigator instance
						$ChanceToShow : 2, //[Required] 0 Never, 1 Mouse Over, 2 Always
						$AutoCenter : 1, //[Optional] Auto center navigator in parent container, 0 None, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
						$Steps : 1, //[Optional] Steps to go for each navigation request, default value is 1
						$Lanes : 1, //[Optional] Specify lanes to arrange items, default value is 1
						$SpacingX : 8, //[Optional] Horizontal space between each item in pixel, default value is 0
						$SpacingY : 8, //[Optional] Vertical space between each item in pixel, default value is 0
						$Orientation : 1 //[Optional] The orientation of the navigator, 1 horizontal, 2 vertical, default value is 1
					},

					$ArrowNavigatorOptions : {//[Optional] Options to specify and enable arrow navigator or not
						$Class : $JssorArrowNavigator$, //[Requried] Class to create arrow navigator instance
						$ChanceToShow : 1, //[Required] 0 Never, 1 Mouse Over, 2 Always
						$AutoCenter : 2, //[Optional] Auto center arrows in parent container, 0 No, 1 Horizontal, 2 Vertical, 3 Both, default value is 0
						$Steps : 1 //[Optional] Steps to go for each navigation request, default value is 1
					}
				};

				var jssor_slider1 = new $JssorSlider$(containerId, options);

				//responsive code begin
				//you can remove responsive code if you don't want the slider scales while window resizes
				function ScaleSlider() {
					var bodyWidth = document.getElementById("cerramie").clientWidth;
					if (bodyWidth)
						jssor_slider1.$ScaleWidth(Math.min(bodyWidth, 1920));
					else
						$Jssor$.$Delay(ScaleSlider, 30);
				}

				ScaleSlider();
				$Jssor$.$AddEvent(window, "load", ScaleSlider);

				$Jssor$.$AddEvent(window, "resize", $Jssor$.$WindowResizeFilter(window, ScaleSlider));
				$Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
				//responsive code end
			};
		</script>
		<!--#region Bullet Navigator Skin Begin -->
		<style>
			/* jssor slider bullet navigator skin 21 css */
			/*
			 .jssorb21 div           (normal)
			 .jssorb21 div:hover     (normal mouseover)
			 .jssorb21 .av           (active)
			 .jssorb21 .av:hover     (active mouseover)
			 .jssorb21 .dn           (mousedown)
			 */
			.jssorb21 {
				position: absolute;
			}
			.jssorb21 div, .jssorb21 div:hover, .jssorb21 .av {
				position: absolute;
				/* size of bullet elment */
				width: 19px;
				height: 19px;
				text-align: center;
				line-height: 19px;
				color: white;
				font-size: 12px;
				background: url(../assets/b21.png) no-repeat;
				overflow: hidden;
				cursor: pointer;
			}
			.jssorb21 div {
				background-position: -5px -5px;
			}
			.jssorb21 div:hover, .jssorb21 .av:hover {
				background-position: -35px -5px;
			}
			.jssorb21 .av {
				background-position: -65px -5px;
			}
			.jssorb21 .dn, .jssorb21 .dn:hover {
				background-position: -95px -5px;
			}
		</style>
		<!--#region Arrow Navigator Skin Begin -->
		<style>
			/* jssor slider arrow navigator skin 21 css */
			/*
			 .jssora21l                  (normal)
			 .jssora21r                  (normal)
			 .jssora21l:hover            (normal mouseover)
			 .jssora21r:hover            (normal mouseover)
			 .jssora21l.jssora21ldn      (mousedown)
			 .jssora21r.jssora21rdn      (mousedown)
			 */
			.jssora21l, .jssora21r {
				display: block;
				position: absolute;
				/* size of arrow element */
				width: 55px;
				height: 55px;
				cursor: pointer;
				background: url(../assets/a21.png) center center no-repeat;
				overflow: hidden;
			}
			.jssora21l {
				background-position: -3px -33px;
			}
			.jssora21r {
				background-position: -63px -33px;
			}
			.jssora21l:hover {
				background-position: -123px -33px;
			}
			.jssora21r:hover {
				background-position: -183px -33px;
			}
			.jssora21l.jssora21ldn {
				background-position: -243px -33px;
			}
			.jssora21r.jssora21rdn {
				background-position: -303px -33px;
			}
		</style>
		<div class="page">
			<!--========================================================
			CONTENT
			=========================================================-->
				<main>
					<section class="well well__ins2 bg-primary">
						<div class="container">
							<h3 class="primary-color"><%=@traducciones.find(80).frances%></h3>

							<div class="row">
								<div id="cerramie" class="grid_4">
									<!-- Jssor Slider Begin -->
									<!-- To move inline styles to css file/block, please specify a class name for each element. -->
									<div id="slider3_container" style="position: relative; margin: 0 auto;
									top: 0px; left: 0px; width: 1300px; height: 1000px; overflow: hidden;">
										<!-- Loading Screen -->
										<div u="loading" style="position: absolute; top: 0px; left: 0px;">
											<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block;
											top: 0px; left: 0px; width: 100%; height: 100%;"></div>
											<div style="position: absolute; display: block; background: url(../assets/loading.gif) no-repeat center center;
											top: 0px; left: 0px; width: 100%; height: 100%;"></div>
										</div>
										<!-- Slides Container -->
										<div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1300px;
										height: 1000px; overflow: hidden;">
											<div>
												<img u="image" src="../assets/Cerramiento1.jpg" />
											</div>
											<div>
												<img u="image" src="../assets/Cerramiento2.jpg" />
											</div>
											<div>
												<img u="image" src="../assets/cerramientoProductos.JPG" />
											</div>
										</div>

										<!-- bullet navigator container -->
										<div u="navigator" class="jssorb21" style="bottom: 26px; right: 6px;">
											<!-- bullet navigator item prototype -->
											<div u="prototype"></div>
										</div>
										<!--#endregion Bullet Navigator Skin End -->

										<!-- Arrow Left -->
										<span u="arrowleft" class="jssora21l" style="top: 123px; left: 8px;"> </span>
										<!-- Arrow Right -->
										<span u="arrowright" class="jssora21r" style="top: 123px; right: 8px;"> </span>
										<!--#endregion Arrow Navigator Skin End -->
									</div>
									<!-- Trigger -->
									<script>
										jssor_slider1_starter('slider3_container');
									</script>
									<!-- Jssor Slider End -->
								</div>
								<div class="grid_8">
									<h5><%=@traducciones.find(123).frances%></h5>
									<p>
										<%=@traducciones.find(124).frances%><br /><br />
<%=@traducciones.find(125).frances%><br /><br />
<%=@traducciones.find(126).frances%> <%=link_to @traducciones.find(127).frances, fr_home_path(:anchor => "contacto")%><%=@traducciones.find(128).frances%><br /><br />
<%=@traducciones.find(129).frances%>
									</p>
								</div>
							</div>
						</div>
					</section>

				</main>
		</div>
	</body>
</html>

app/views/fr/cristalInteligente.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <title><%=@traducciones.find(81).frances%></title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
<% activo "","","","active","","" %>
<% idioma "fr" %>
<% user @current_user %>
</head>
<body>
<div class="page">
    <!--========================================================
                              CONTENT
    =========================================================-->
    <main>
        <section class="well well__ins2 bg-primary">
            <div class="container">
                <h3 class="primary-color"><%=@traducciones.find(81).frances%></h3>

                <div class="row">
                    <div class="grid_4">
                        <img class="img-add" src="../assets/infografia-climalit-general.jpg" alt=""/></div>
                    <div class="grid_8">
                        <h5><%=@traducciones.find(130).frances%></h5><br />
                        <p><%=@traducciones.find(131).frances%></p><br />
 <h5><%=@traducciones.find(132).frances%></h5><br />
                        <p><%=@traducciones.find(133).frances%></p>
                         
                         <a class="btn1" href="http://www.climalit.es/climalit-plus-info/" target="_blank"><%=@traducciones.find(43).frances%> >></a>
					</div>
                </div>
            </div>
        </section>

    </main>
</div>
</body>
</html>

app/views/fr/nuestrosProductos.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <title><%=@traducciones.find(35).frances%></title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
 <% activo "","active","","","","" %>
 <% idioma "fr" %>
 <% user @current_user %>
</head>
<body>
<div class="page">
    <!--========================================================
                              CONTENT
    =========================================================-->
    <main>
        <section class="well well__ins2 bg-primary">
            <div class="container">
                <h3 class="primary-color"><%=@traducciones.find(35).frances%></h3>

                <div class="row">
                    <div class="grid_4">
                        <img class="img-add" src="../assets/nuestrosProductos.PNG" alt=""/></div>
                    <div class="grid_8">
                        <h5><%=@traducciones.find(36).frances%>
                        	<br />
                        	<%=@traducciones.find(37).frances%>
                        	</h5>
                        	<div class="row">
<div class="grid_4" style="width: 100%">
                                <ul class="marked-list offset2">
                                      <li><a ><%=@traducciones.find(38).frances%></a></li>
                                    <li><%=@traducciones.find(39).frances%> <%=link_to fr_couleurs_et_feuillete_path do%><strong><u><%=@traducciones.find(40).frances%></u></strong> <%end%> <%=@traducciones.find(41).frances%></li>
                                <li><a ><%=@traducciones.find(42).frances%></a></li>
                                 
                                </ul>
                       
                            </div>
                            </div>
                        <%=link_to fr_produits_path, :class => "btn1" do%><%=@traducciones.find(43).frances%> >><%end%>
					</div>
                </div>
            </div>
        </section>

    </main>
    <section class="well bg-primary">
        <div class="container">
            <div class="row">
                <div class="grid_6 wow fadeInLeft">
                    <h3 class="primary-color"><%=@traducciones.find(44).frances%></h3>
                    <ul class="index-list index-list1">
                        <li>
                            <div class="wrapper">
                                <h5 class="strong"><%=@traducciones.find(45).frances%></h5>

                            </div>
                        </li>

                        <li>
                            <div class="wrapper">
                                <h5 class="strong"><%=@traducciones.find(46).frances%></h5>
                            </div>
                        </li>
                        <li>
                            <div class="wrapper">
                                <h5 class="strong"><%=@traducciones.find(47).frances%></h5>
                            </div>
                        </li>
                          <li>
                            <div class="wrapper">
                                <h5 class="strong"><%=@traducciones.find(48).frances%></h5>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="grid_6 wow fadeInLeft">
                    <h3 class="primary-color"></h3>
                    <ul class="index-list index-list2">
                          <li>
                            <div class="wrapper">
                                <h5 class="strong"><%=@traducciones.find(49).frances%></h5>
                            </div>
                        </li>
                          <li>
                            <div class="wrapper">
                                <h5 class="strong"><%=@traducciones.find(50).frances%></h5>
                            </div>
                        </li>
                           <li>
                            <div class="wrapper">
                                <h5 class="strong"><%=@traducciones.find(51).frances%></h5>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
</div>
</body>
</html>

app/views/fr/productos.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
    <title><%=@traducciones.find(77).frances%></title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
  <% activo "","","","active","","" %>
  <% idioma "fr" %>
  <% user @current_user %>
</head>
<body>
<div class="page">
    <!--========================================================
                              CONTENT
    =========================================================-->
    <main>
        <section class="well border">
            <div class="container">
                <h3 class=" primary-color"><%=@traducciones.find(77).frances%></h3>

                <div class="row">
                    <div class="grid_3 wow fadeInLeft">
                        <%=link_to fr_fenetres_path do%><div class="resp-center"><img src="../assets/ventanaProductos.jpg" alt=""/></div>
                        <h5 class="strong"><%=@traducciones.find(78).frances%></h5><%end%>

                    </div>
                    <div class="grid_3 wow fadeInLeft">
                       <%=link_to fr_portes_path do%> <div class="resp-center">
                            <img src="../assets/puerta.JPG" alt=""/>
                        </div>
                        <h5 class="strong"><%=@traducciones.find(79).frances%></h5><%end%>

                    </div>
                    <div class="grid_3 wow fadeInRight">
                       <%=link_to fr_boitiers_path do%> <div class="resp-center">
                            <img src="../assets/cerramientoProductos.JPG" alt=""/>
                        </div>
                        <h5 class="strong"><%=@traducciones.find(80).frances%></h5><%end%>

                    </div>
                    <div class="grid_3  wow fadeInRight">
                        <%=link_to fr_verreIntelligent_path do%><div class="resp-center"><img src="../assets/imagenes-cabecera-climalit.png" alt=""/>
                        </div>
                        <h5 class="strong"><%=@traducciones.find(81).frances%></h5><%end%>

                    </div>
                </div>
            </div>
        </section>
    </main>
</div>
</body>
</html>