config/routes.rb
Rails.application.routes.draw do
  resources :trabajos
  resources :usuarios
  resources :diccionarios
  resources :articulos
  
  root :to => redirect('/es/inicio')
  get 'es/inicio' => 'es#home'
  get 'es/colores-y-foliados'=> 'es#coloresFoliados'
  get 'es/nuestraEmpresa'=> 'es#nuestraEmpresa'
  get 'es/nuestrosProductos'=> 'es#nuestrosProductos'
  get 'es/garantia'=> 'es#garantia'
  get 'es/materialesCalidad'=> 'es#materialesCalidad'
  get 'es/productos'=> 'es#productos'
  get 'es/ventanas'=> 'es#ventanas'
  get 'es/puertas'=> 'es#puertas'
  get 'es/cerramientos'=> 'es#cerramientos'
  get 'es/cristalInteligente'=> 'es#cristalInteligente'
  get 'es/trabajos'=> 'es#trabajos'
  get 'es/blog'=> 'es#blog'
  get 'es/articuloBlog/:id'=> 'es#articuloBlog', as: :articuloBlogEs
  get 'es/avisoLegal' => 'es#avisoLegal'
    get 'en/home' => 'en#home'
  get 'en/colors-and-foliated'=> 'en#coloresFoliados'
  get 'en/ourCompany'=> 'en#nuestraEmpresa'
  get 'en/ourProducts'=> 'en#nuestrosProductos'
  get 'en/warranty'=> 'en#garantia'
  get 'en/qualityMaterials'=> 'en#materialesCalidad'
  get 'en/products'=> 'en#productos'
  get 'en/windows'=> 'en#ventanas'
  get 'en/doors'=> 'en#puertas'
  get 'en/enclosures'=> 'en#cerramientos'
  get 'en/intelligentGlass'=> 'en#cristalInteligente'
  get 'en/works'=> 'en#trabajos'
  get 'en/blog'=> 'en#blog'
  get 'en/articleBlog/:id'=> 'en#articuloBlog', as: :articuloBlogEn
    get 'fr/home' => 'fr#home'
  get 'fr/couleurs-et-feuillete'=> 'fr#coloresFoliados'
  get 'fr/notreSociete'=> 'fr#nuestraEmpresa'
  get 'fr/nosProduits'=> 'fr#nuestrosProductos'
  get 'fr/garantie'=> 'fr#garantia'
  get 'fr/materiauxQualite'=> 'fr#materialesCalidad'
  get 'fr/produits'=> 'fr#productos'
  get 'fr/fenetres'=> 'fr#ventanas'
  get 'fr/portes'=> 'fr#puertas'
  get 'fr/boitiers'=> 'fr#cerramientos'
  get 'fr/verreIntelligent'=> 'fr#cristalInteligente'
  get 'fr/travaux'=> 'fr#trabajos'
  get 'fr/blog'=> 'fr#blog'
  get 'fr/articleBlog/:id'=> 'fr#articuloBlog', as: :articuloBlogFr
    get 'de/home' => 'de#home'
  get 'de/farben-und-foliated'=> 'de#coloresFoliados'
  get 'de/unserUnternehmen'=> 'de#nuestraEmpresa'
  get 'de/unsereProdukte'=> 'de#nuestrosProductos'
  get 'de/garantie'=> 'de#garantia'
  get 'de/werkstoffeQualitat'=> 'de#materialesCalidad'
  get 'de/produkte'=> 'de#productos'
  get 'de/fenster'=> 'de#ventanas'
  get 'de/turen'=> 'de#puertas'
  get 'de/gehause'=> 'de#cerramientos'
  get 'de/intelligentGlas'=> 'de#cristalInteligente'
  get 'de/arbeit'=> 'de#trabajos'
  get 'de/blog'=> 'de#blog'
  get 'de/artikelBlog/:id'=> 'de#articuloBlog', as: :articuloBlogDe
  
  get 'delDiccionario/:id'=> 'diccionarios#destroy', as: :delDicionario
  get 'delUsuario/:id'=> 'usuarios#destroy', as: :delUsuario
  get 'delArticulo/:id'=> 'articulos#destroy', as: :delArticulo
  get 'delTrabajo/:id'=> 'trabajos#destroy', as: :delTrabajo
  get 'login'=>'es#login'
  post 'entrar'=>'es#entrar'
  get 'salir'=>'es#salir'
  
  get '*path' => redirect('/es/inicio')

end

app/controllers/es_controller.rb
class EsController < ApplicationController
  def home
    current_user
  end
  def nuestraEmpresa
    current_user
  end
  def nuestrosProductos
    current_user
  end
  def garantia
    current_user
  end
  def materialesCalidad
    current_user
  end
  def productos
    current_user
  end
  def ventanas
    current_user
  end
  def puertas
    current_user
  end
  def cerramientos
    current_user
  end
  def cristalInteligente
    current_user
  end
  def trabajos
    current_user
    @trabajos = Trabajo.all.sort_by{|e| e[:nombreTrabajo]}
  end
  def blog
    current_user
    @articulosBlog=Articulo.all.reverse
  end
  def articuloBlog
    current_user
    @articulo=Articulo.find(params[:id])
  end
  def coloresFoliados
    current_user
  end
  def avisoLegal
    current_user
  end
  def login
    current_user
    @error=""
    @user= Usuario.new
  end
  def entrar
    user = Usuario.find_by(username: params[:usuario][:username])
    if user == nil
      @error="Información incorrecta"
      @user=Usuario.new
      render 'login'
    else
    if user.password.eql? params[:usuario][:password]
      log_in user
      current_user
      if @current_user.tipo=="Administrador"
      redirect_to usuarios_path
      end
      if @current_user.tipo=="Traductor"
        redirect_to diccionarios_path
      end
      if @current_user.tipo=="Blogger"
        redirect_to articulos_path
      end
    else
      @error="Información incorrecta"
      @user=Usuario.new
      render 'login'
    end
  end
  end
  def salir
    log_out
    redirect_to es_inicio_path
  end
end

app/helpers/es_helper.rb
module EsHelper
  
end

app/views/es/avisoLegal.html.erb
<!DOCTYPE html>
<html lang="es-ES">
<head>
    <title>Aviso Legal</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
<% activo "","","","","","" %>
<% idioma "es" %>
<% user @current_user %>
</head>
<body>
<div class="page">
    <!--========================================================
                              CONTENT
    =========================================================-->
    <main>
        <section class="well well__ins2 bg-primary">
            <div class="container">
                <h3 class="primary-color">Aviso legal. Términos de uso.</h3>

                <div class="row">
                        <h5>Aviso legal.</h5>
                        <p>El presente portal "www.ventanastalleresmazo.com" (en adelante, el “portal“) es titularidad de URCIPLAST, S.L., (en adelante, “El prestador“), quien lo pone a disposición de los usuarios, personas físicas y jurídicas, de Internet con el fin de, entre otros, proporcionar y permitir información sobre los productos, servicios y ofertas de TALLERES MAZO.<br /><br />

Nuestros datos son los siguientes:<br /><br />

URCIPLAST, S.L. <br />
Ctra. Comarcal 332, Km. 1.2, 04400 - Alhama de Almería, España. <br />
C.I.F. nº: B-04220497 <br />
Inscrita en el Registro Mercantil de Almería en el Tomo 225-AL de Sociedades, Folio 178, Hoja 6455-AL, Inscripción 1ª. <br />
Dirección de correo electrónico: talleres.mazo@gmail.com <br />
Teléfono: 950 26 37 22<br /><br />
                        	Toda persona que acceda a este sitio web asume el papel de usuario, comprometiéndose a la observancia y cumplimiento riguroso de las disposiciones aquí dispuestas, así como a cualquier otra disposición legal que fuera de aplicación. El prestador se exime de cualquier tipo de responsabilidad derivada de la información publicada en su sitio web y por la falta de disponibilidad (caídas) del sitio el cual efectuará además paradas periódicas por mantenimientos técnicos. Además, el prestador se reserva el derecho a modificar cualquier tipo de información que pudiera aparecer en el sitio web, sin que exista obligación de preavisar o poner en conocimiento de los usuarios dichas obligaciones, entendiéndose como suficiente con la publicación en el sitio web del prestador.</p>
                        <br /><h5>Política de privacidad.</h5>
                        <p>Por medio de nuestra política de privacidad le ponemos al tanto de los debidos términos de uso en este sitio.</p>

<p>La utilización de estos implica su aceptación plena y sin reservas a todas y cada una de las disposiciones incluidas en este Aviso Legal, por lo que si usted no está de acuerdo con cualquiera de las condiciones aquí establecidas, no deberá usar u/o acceder a este sitio. Reservamos el derecho a modificar esta Declaración de Privacidad en cualquier momento. Su uso continuo de cualquier porción de este sitio tras la notificación o anuncio de tales modificaciones constituirá su aceptación de tales cambios.</p>
	<br /><h5>Acciones de terceros.</h5>
	<p>Así mismo, usted encontrará dentro de este sitio, páginas, micrositios, contratistas y/o socios y servicios comerciales, en conjunto con otros servicios compartidos, propios o cobrandeados con terceros (”Sitios Cobrandeados”) que le podrán solicitar Información, los cuales este sitio le podrá revelar información proporcionada por usted.<br />
La Información que se proporcione en estos Sitios Cobrandeados esta sujeta a las políticas de privacidad o leyendas de responsabilidad de Información que se desplieguen en dichos Sitios y no estará sujeta a esta política de privacidad. Por lo que recomendamos ampliamente a los Usuarios a revisar detalladamente las políticas de privacidad que se desplieguen en los Sitios Cobrandeados.</p>
				<br /><h5>Política de Protección de Datos Personales</h5>
				<p>Los datos enviados a nuestro correo electrónico, facilitados por usted, en caso de establecer una factura/presupuesto, serán incorporados en un fichero llamado "CLIENTES/PROVEEDORES" cuyo titular es URCIPLAST, S.L. y con la finalidad del tratamiento contable, comunicación con el cliente y acciones comerciales. Para ejercer su derecho de acceso, rectificación, cancelación u oposición, pueden dirigirse a URCIPLAST, S.L.; CRTA. RONDA 76, FRENTE AL MERCADONA, 04006 - ALMERÍA. Teléfono: 950263722, Fax: 950277382; E-mail: talleres.mazo@gmail.com</p>
				<br /><h5>Ley Aplicable y Jurisdicción</h5>
				<p>Para la resolución de todas las controversias o cuestiones relacionadas con el presente sitio web, será de aplicación la legislación española, a la que se someten expresamente ambas partes.</p>
				</div>
			</div>
        </section>

    </main>
</div>
</body>
</html>

app/views/es/coloresFoliados.html.erb
<!DOCTYPE html>
<html lang="es-ES">
<head>
    <title>Colores y Foliados</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
<% activo "","active","","","","" %>
<% idioma "es" %>
<% user @current_user %>
</head>
<body>
<div class="page">
    <!--========================================================
                              CONTENT
    =========================================================-->
    <section class="well border" style="background-color: white;">
            <div class="container">
                <h3 class=" primary-color">Colores</h3>

                <div class="row">
                    <div class="grid_3 wow fadeInLeft">
                        <div class="resp-center"><img src="../assets/color-blanco.jpg" alt=""/></div>
                        <h5 class="strong">Blanco</h5>
                    </div>
                </div>
            </div>
        </section>
        <section class="well border" style="background-color: white;">
            <div class="container">
                <h3 class=" primary-color">Foliados</h3>

                <div class="row">
                    <div class="grid_3 wow fadeInLeft">
                        <div class="resp-center"><img src="../assets/color-roble-big.jpg" alt=""/></div>
                        <h5 class="strong">Roble oro</h5>
                        </div>
                    <div class="grid_3 wow fadeInLeft">
                        <div class="resp-center">
                            <img src="../assets/color-nogal-big.jpg" alt=""/>
                        </div>
                        <h5 class="strong">Nogal</h5>
                    </div>
                    <div class="grid_3 wow fadeInRight">
                        <div class="resp-center">
                            <img src="../assets/montana.jpg" alt=""/>
                        </div>
                        <h5 class="strong">Montana</h5>
                    </div>
                    <div class="grid_3 wow fadeInRight">
                        <div class="resp-center">
                            <img src="../assets/antracita.jpg" alt=""/>
                        </div>
                        <h5 class="strong">Antracita</h5>
                    </div>
                </div>
            </div>
        </section>
<section class="well border" style="background-color: white;">
            <div class="container">
                <h3 class=" primary-color">Lacados: Toda la gama de colores RAL</h3>

                <div class="row">
                    <a href="http://ralcolor.com/" target="_blank"><div class="grid_3 wow fadeInLeft">
                        <div class="resp-center"><img src="../assets/RAL.jpg" alt=""/></div>
                    </div></a>
                </div>
            </div>
        </section>

</div>
</body>
</html>

app/views/es/login.html.erb
<!DOCTYPE html>
<html lang="es-ES">
<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
<% activo "","","","","","" %>
<% idioma "es" %>
<% user @current_user %>
</head>
<body>
<div class="page">
	<style type="text/css" media="screen">
		@import url(http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300);
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  font-weight: 300;
}
body {
  font-family: 'Source Sans Pro', sans-serif;
  color: white;
  font-weight: 300;
}
body ::-webkit-input-placeholder {
  /* WebKit browsers */
  font-family: 'Source Sans Pro', sans-serif;
  color: white;
  font-weight: 300;
}
body :-moz-placeholder {
  /* Mozilla Firefox 4 to 18 */
  font-family: 'Source Sans Pro', sans-serif;
  color: white;
  opacity: 1;
  font-weight: 300;
}
body ::-moz-placeholder {
  /* Mozilla Firefox 19+ */
  font-family: 'Source Sans Pro', sans-serif;
  color: white;
  opacity: 1;
  font-weight: 300;
}
body :-ms-input-placeholder {
  /* Internet Explorer 10+ */
  font-family: 'Source Sans Pro', sans-serif;
  color: white;
  font-weight: 300;
}
.wrapper {
  background: #50a3a2;
  background: -webkit-linear-gradient(top left, #50a3a2 0%, #53e3a6 100%);
  background: linear-gradient(to bottom right, #50a3a2 0%, #53e3a6 100%);
  position: relative;
  top: 0;
  left: 0;
  width: 100%;
  height: 400px;
  overflow: hidden;
}
.wrapper.form-success .container h1 {
  -webkit-transform: translateY(85px);
      -ms-transform: translateY(85px);
          transform: translateY(85px);
}
.container {
  max-width: 600px;
  margin: 0 auto;
  padding: 80px 0;
  height: 400px;
  text-align: center;
}
.container h1 {
  font-size: 40px;
  -webkit-transition-duration: 1s;
          transition-duration: 1s;
  -webkit-transition-timing-function: ease-in-put;
          transition-timing-function: ease-in-put;
  font-weight: 200;
}
form {
  padding: 20px 0;
  position: relative;
  z-index: 2;
}
form input {
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
  outline: 0;
  border: 1px solid rgba(255, 255, 255, 0.4);
  background-color: rgba(255, 255, 255, 0.2);
  width: 250px;
  border-radius: 3px;
  padding: 10px 15px;
  margin: 0 auto 10px auto;
  display: block;
  text-align: center;
  font-size: 18px;
  color: white;
  -webkit-transition-duration: 0.25s;
          transition-duration: 0.25s;
  font-weight: 300;
}
form input:hover {
  background-color: rgba(255, 255, 255, 0.4);
}
form input:focus {
  background-color: white;
  width: 300px;
  color: #53e3a6;
}
form button {
  -webkit-appearance: none;
     -moz-appearance: none;
          appearance: none;
  outline: 0;
  background-color: white;
  border: 0;
  padding: 10px 15px;
  color: #53e3a6;
  border-radius: 3px;
  width: 250px;
  cursor: pointer;
  font-size: 18px;
  -webkit-transition-duration: 0.25s;
          transition-duration: 0.25s;
}
form button:hover {
  background-color: #f5f7f9;
}
.bg-bubbles {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 1;
}
.bg-bubbles li {
  position: absolute;
  list-style: none;
  display: block;
  width: 40px;
  height: 40px;
  background-color: rgba(255, 255, 255, 0.15);
  bottom: -160px;
  -webkit-animation: square 25s infinite;
  animation: square 25s infinite;
  -webkit-transition-timing-function: linear;
  transition-timing-function: linear;
}
.bg-bubbles li:nth-child(1) {
  left: 10%;
}
.bg-bubbles li:nth-child(2) {
  left: 20%;
  width: 80px;
  height: 80px;
  -webkit-animation-delay: 2s;
          animation-delay: 2s;
  -webkit-animation-duration: 17s;
          animation-duration: 17s;
}
.bg-bubbles li:nth-child(3) {
  left: 25%;
  -webkit-animation-delay: 4s;
          animation-delay: 4s;
}
.bg-bubbles li:nth-child(4) {
  left: 40%;
  width: 60px;
  height: 60px;
  -webkit-animation-duration: 22s;
          animation-duration: 22s;
  background-color: rgba(255, 255, 255, 0.25);
}
.bg-bubbles li:nth-child(5) {
  left: 70%;
}
.bg-bubbles li:nth-child(6) {
  left: 80%;
  width: 120px;
  height: 120px;
  -webkit-animation-delay: 3s;
          animation-delay: 3s;
  background-color: rgba(255, 255, 255, 0.2);
}
.bg-bubbles li:nth-child(7) {
  left: 32%;
  width: 160px;
  height: 160px;
  -webkit-animation-delay: 7s;
          animation-delay: 7s;
}
.bg-bubbles li:nth-child(8) {
  left: 55%;
  width: 20px;
  height: 20px;
  -webkit-animation-delay: 15s;
          animation-delay: 15s;
  -webkit-animation-duration: 40s;
          animation-duration: 40s;
}
.bg-bubbles li:nth-child(9) {
  left: 25%;
  width: 10px;
  height: 10px;
  -webkit-animation-delay: 2s;
          animation-delay: 2s;
  -webkit-animation-duration: 40s;
          animation-duration: 40s;
  background-color: rgba(255, 255, 255, 0.3);
}
.bg-bubbles li:nth-child(10) {
  left: 90%;
  width: 160px;
  height: 160px;
  -webkit-animation-delay: 11s;
          animation-delay: 11s;
}
@-webkit-keyframes square {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-700px) rotate(600deg);
            transform: translateY(-700px) rotate(600deg);
  }
}
@keyframes square {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    -webkit-transform: translateY(-700px) rotate(600deg);
            transform: translateY(-700px) rotate(600deg);
  }
}
body{
	background-color: white;
}
	</style>
	    <!--========================================================
                              CONTENT
    =========================================================-->
    <section class="well border" style="background-color: white;">
<div class="wrapper">
	<div class="container">
		<h1>Bienvenido</h1>
		<p><%=@error%></p>
		<%= form_for(@user, url: entrar_path) do |f| %>
			<input type="text" name="usuario[username]" id="usuario_username" required placeholder="Username">
			<input type="password" name="usuario[password]" id="usuario_password" required placeholder="Password">
			<%=f.submit "Login"%>
		<%end%>
	</div>
	
	<ul class="bg-bubbles">
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
		<li></li>
	</ul>
</div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

        <script>
        	 $("#login-button").click(function(event){
		 event.preventDefault();
	 
	 $('form').fadeOut(500);
	 $('.wrapper').addClass('form-success');
});
        </script>>

        </section>

</div>
</body>
</html>

app/views/es/nuestrosProductos.html.erb
<!DOCTYPE html>
<html lang="es-ES">
<head>
    <title>Nuestros Productos</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
 <% activo "","active","","","","" %>
 <% idioma "es" %>
 <% user @current_user %>
</head>
<body>
<div class="page">
    <!--========================================================
                              CONTENT
    =========================================================-->
    <main>
        <section class="well well__ins2 bg-primary">
            <div class="container">
                <h3 class="primary-color">Nuestros productos</h3>

                <div class="row">
                    <div class="grid_4">
                        <img class="img-add" src="../assets/nuestrosProductos.PNG" alt=""/></div>
                    <div class="grid_8">
                        <h5>Fabricamos Puertas y Ventanas a la medida sin importar el tamaño o la forma que desees que estas tengan. También contamos con una amplia gama de colores, acabados y aperturas para cualquier necesidad.
                        	<br />
                        	Nuestros productos poseen un alto nivel de aislamiento térmico y acústico que ayuda a ahorrar energía y crear un ambiente de comodidad en el hogar, además nuestras puertas y ventanas son de alta seguridad y de muy bajo mantenimiento.
                        	</h5>
                        	<div class="row">
<div class="grid_4" style="width: 100%">
                                <ul class="marked-list offset2">
                                      <li><a >TIPOS DE APERTURA DISPONIBLES: Practicable, Oscilobatiente, Osciloparalela, Practicable de apertura exterior, Corredera, Plegable y Elevadora.</a></li>
                                    <li>ACABADOS: Blanco masa, <%=link_to es_colores_y_foliados_path do%><strong><u>FOLIADOS</u></strong> <%end%> y Lacado.</li>
                                <li><a >POSIBILIDAD DE MOTORIZACIÓN: SI.</a></li>
                                 
                                </ul>
                       
                            </div>
                            </div>
                        <%=link_to es_productos_path, :class => "btn1" do%>Más información >><%end%>
					</div>
                </div>
            </div>
        </section>

    </main>
    <section class="well bg-primary">
        <div class="container">
            <div class="row">
                <div class="grid_6 wow fadeInLeft">
                    <h3 class="primary-color">Beneficios</h3>
                    <ul class="index-list index-list1">
                        <li>
                            <div class="wrapper">
                                <h5 class="strong">Es resistente </h5>

                            </div>
                        </li>

                        <li>
                            <div class="wrapper">
                                <h5 class="strong">Es duradero</h5>
                            </div>
                        </li>
                        <li>
                            <div class="wrapper">
                                <h5 class="strong">Es impermeable a gases y líquidos</h5>
                            </div>
                        </li>
                          <li>
                            <div class="wrapper">
                                <h5 class="strong">Es auto-extinguible</h5>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="grid_6 wow fadeInLeft">
                    <h3 class="primary-color"></h3>
                    <ul class="index-list index-list2">
                          <li>
                            <div class="wrapper">
                                <h5 class="strong">Gran capacidad de aislamiento térmico y acústico</h5>
                            </div>
                        </li>
                          <li>
                            <div class="wrapper">
                                <h5 class="strong">Magníficos acabados superficiales</h5>
                            </div>
                        </li>
                           <li>
                            <div class="wrapper">
                                <h5 class="strong">Facilidad de mantenimiento</h5>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
</div>
</body>
</html>

app/views/es/productos.html.erb
<!DOCTYPE html>
<html lang="es-ES">
<head>
    <title>Productos</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no"/>
  <% activo "","","","active","","" %>
  <% idioma "es" %>
  <% user @current_user %>
</head>
<body>
<div class="page">
    <!--========================================================
                              CONTENT
    =========================================================-->
    <main>
        <section class="well border">
            <div class="container">
                <h3 class=" primary-color">Productos</h3>

                <div class="row">
                    <div class="grid_3 wow fadeInLeft">
                        <%=link_to es_ventanas_path do%><div class="resp-center"><img src="../assets/ventanaProductos.jpg" alt=""/></div>
                        <h5 class="strong">Ventanas</h5><%end%>

                    </div>
                    <div class="grid_3 wow fadeInLeft">
                       <%=link_to es_puertas_path do%> <div class="resp-center">
                            <img src="../assets/puerta.JPG" alt=""/>
                        </div>
                        <h5 class="strong">Puertas</h5><%end%>

                    </div>
                    <div class="grid_3 wow fadeInRight">
                       <%=link_to es_cerramientos_path do%> <div class="resp-center">
                            <img src="../assets/cerramientoProductos.JPG" alt=""/>
                        </div>
                        <h5 class="strong">Cerramientos</h5><%end%>

                    </div>
                    <div class="grid_3  wow fadeInRight">
                        <%=link_to es_cristalInteligente_path do%><div class="resp-center"><img src="../assets/imagenes-cabecera-climalit.png" alt=""/>
                        </div>
                        <h5 class="strong">Cristal inteligente</h5><%end%>

                    </div>
                </div>
            </div>
        </section>
    </main>
</div>
</body>
</html>